[package]
authors = ["Sam Scott <sam@osohq.com>"]
edition = "2018"
categories = ["encoding", "web-programming"]
description = "Querystrings for Serde"
documentation = "https://docs.rs/serde_qs"
keywords = ["serde", "serialization", "querystring"]
license = "MIT/Apache-2.0"
name = "serde_qs"
repository = "https://github.com/samscott89/serde_qs"
readme = "README.md"
version = "0.8.3"

[dependencies]
actix-web = { version = "3.3.2", optional = true, package = "actix-web" }
actix-web2 = { package = "actix-web", version = "2.0.0", optional = true }
futures = { version = "0.3.13", optional = true }
percent-encoding = "2.1.0"
serde = "1.0.124"
thiserror = "1.0.24"
tracing = { version = "0.1.25", optional = true }
validator = { version = ">=0.11, <=0.12", features = ["derive"], optional = true }
warp-framework = { package = "warp", version = "0.3.0", default-features = false, optional = true }

[dev-dependencies]
csv = "1.1.6"
rand = "0.8.3"
serde_derive = "1.0.124"
serde_urlencoded = "0.7.0"

[features]
default = []
actix = ["actix-web", "futures"]
actix2 = ["actix-web2", "futures"]
actix-validator = ["actix", "validator"]
actix2-validator = ["actix2", "validator"]
warp = [ "futures", "tracing", "warp-framework" ]

[package.metadata.docs.rs]
features = [ "actix", "warp" ]
